### ISSUE TITLE
Create backend upload functionality

### ISSUE THREAD

**Issue by NoFrust** [chaozkid/ASWE-SmartArt#4]
US:
10 - I want to display pictures which were uploaded to my channel so that users can see their pictures.
(12 - I want to provide possibilities to upload new images to my channel so that I can display them.)

**Comment by NoFrust** [comment]
Given a picture is ready to be uploaded when the backend is issued to upload the picture then it will be stored and mapped to a certain screen.

**Comment by akramer-dozent** [comment]
2h confirmed

**Comment by akramer-dozent** [comment]
done
