### ISSUE TITLE
Add frontend functionality to vote for pictures

### ISSUE THREAD

**Issue by NoFrust** [chaozkid/ASWE-SmartArt#5]
US:
2 - I want to vote pictures so that I can signalize my favor for a specific picture.

**Comment by NoFrust** [comment]
Given there are pictures on a screen when a user wants to upvote a specific picture then he can vote it up on the mobile frontend of the corresponding screen.

**Comment by akramer-dozent** [comment]
+ thumbnail. 2h confirmed
