### ISSUE TITLE
Add geolocation based mapping

### ISSUE THREAD

**Issue by NoFrust** [chaozkid/ASWE-SmartArt#8]
US:
6 - I want to upload a picture to the SmartArt website so that it can be displayed on screens nearby.

Given a user is at a location when he uploads a picture then an algorithm determines the closest screen will show the uploaded picture.

**Comment by NoFrust** [comment]
Given a user is at a location when he uploads a picture then the closest screen will show the uploaded picture.

**Comment by akramer-dozent** [comment]
3h confirmed. ähnlich?

**Comment by akramer-dozent** [comment]
done
